#!/usr/bin/env bash
#
# build_app.sh — assemble "Kickoff Pulse.app", a native macOS wrapper around
# the Streamlit dashboard (see desktop.py).
#
# The bundle is a *thin* launcher: it does not embed Python. It runs the
# project's existing .venv, so it stays small and never needs code-signing
# gymnastics. Rebuild any time with:  ./build_app.sh
#
# By default the app is written to ./build/Kickoff Pulse.app. Drag it into
# /Applications (or right-click > Make Alias and drop the alias in the Dock)
# to keep it in your Dock.

set -euo pipefail
cd "$(dirname "$0")"

PROJECT_DIR="$(pwd)"
APP_NAME="Kickoff Pulse"
BUNDLE_ID="com.kickoffpulse.app"
EXEC_NAME="KickoffPulse"
APP="build/${APP_NAME}.app"
SRC_LOGO="branding/kickoff-pulse-logo-white-bg.png"

green() { printf '\033[0;32m%s\033[0m\n' "$1"; }

# --------------------------------------------------------------------------- #
# 1. Icon (.icns) from the brand logo
# --------------------------------------------------------------------------- #
ICONSET="$(mktemp -d)/KickoffPulse.iconset"
mkdir -p "$ICONSET"
for size in 16 32 128 256 512; do
  sips -z "$size" "$size" "$SRC_LOGO" \
    --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
  d=$((size * 2))
  sips -z "$d" "$d" "$SRC_LOGO" \
    --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
done

# --------------------------------------------------------------------------- #
# 2. Bundle skeleton
# --------------------------------------------------------------------------- #
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/${EXEC_NAME}.icns"

# --------------------------------------------------------------------------- #
# 3. Info.plist
# --------------------------------------------------------------------------- #
cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>${APP_NAME}</string>
  <key>CFBundleDisplayName</key>     <string>${APP_NAME}</string>
  <key>CFBundleIdentifier</key>      <string>${BUNDLE_ID}</string>
  <key>CFBundleExecutable</key>      <string>${EXEC_NAME}</string>
  <key>CFBundleIconFile</key>        <string>${EXEC_NAME}</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleVersion</key>         <string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>LSMinimumSystemVersion</key>  <string>11.0</string>
  <key>NSHighResolutionCapable</key> <true/>
  <key>NSMicrophoneUsageDescription</key>
  <string>Kickoff Pulse listens to your play-by-play narration to track match stats.</string>
</dict>
</plist>
PLIST

# --------------------------------------------------------------------------- #
# 4. Launcher executable (baked with this project's absolute path)
# --------------------------------------------------------------------------- #
cat > "$APP/Contents/MacOS/${EXEC_NAME}" <<LAUNCHER
#!/usr/bin/env bash
# Auto-generated by build_app.sh — do not edit; rebuild instead.
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR}"
cd "\$PROJECT_DIR"

LOG="\$HOME/Library/Logs/KickoffPulse.log"
mkdir -p "\$(dirname "\$LOG")"
exec >>"\$LOG" 2>&1
echo "==== \$(date) launching Kickoff Pulse ===="

# Apps launched from Finder/Dock inherit launchd's low file-descriptor limit
# (256), which makes Streamlit's file watcher + numpy fail with
# "Too many open files". Terminal sessions get a higher limit, which is why
# kickoff.sh works. Raise it here to match.
ulimit -n 4096 2>/dev/null || true

# Optional per-machine settings (e.g. KICKOFF_MIC="AirPods"). Finder/Dock
# launches do NOT load your shell profile, so put env vars here instead.
[ -f "\$PROJECT_DIR/.env" ] && set -a && . "\$PROJECT_DIR/.env" && set +a

# First-run safety net: create the venv + install deps if missing.
if [ ! -x ".venv/bin/python" ]; then
  python3 -m venv .venv
  .venv/bin/pip install --upgrade pip
  .venv/bin/pip install -r requirements.txt
fi

# Best-effort: make sure Ollama (The Brain) is serving so speech gets parsed.
if command -v ollama >/dev/null 2>&1 && \
   ! curl -fsS "\${OLLAMA_URL:-http://localhost:11434}/api/version" >/dev/null 2>&1; then
  nohup ollama serve >/tmp/ollama.log 2>&1 &
  sleep 3
fi

# Match library: use Docker Postgres if it's up, else SQLite (db.py default).
if [ -z "\${KICKOFF_DB_URL:-}" ] && (: < /dev/tcp/localhost/5432) 2>/dev/null; then
  export KICKOFF_DB_URL="postgresql+psycopg://kickoff:kickoff@localhost:5432/kickoff"
fi

# The venv's Python is a universal2 binary. Launched from Finder/Dock, macOS
# may default it to the x86_64 slice, but the installed wheels (mlx, torch,
# numpy) are native-arch only -> "incompatible architecture". Pin to the
# machine's native arch so it matches a normal terminal launch.
ARCH="\$(uname -m)"
echo "[launcher] arch=\$ARCH project=\$PROJECT_DIR"
exec arch "-\$ARCH" .venv/bin/python desktop.py
LAUNCHER
chmod +x "$APP/Contents/MacOS/${EXEC_NAME}"

# Refresh Finder/Dock icon caches for this bundle.
touch "$APP"

green "Built ${APP}"
echo "  Drag it into /Applications, then keep it in your Dock."
